### ISSUE TITLE
Add reroll command

### ISSUE THREAD

**Issue by Alan19** [Alan19/TwoDee#22]

**Comment by belathus** [comment]
Reroll command refunds plot points and rerolls the plot die, but you end up at the same amount of plot points that you started with.

**Comment by Alan19** [comment]
Isn't that what rerolling should do? I thought rerolling with inspired reverts all point changes and rolls the same pool again.

**Comment by belathus** [comment]
The event that made me comment on this was that Myles had used a pd12 on a roll that she was good at and rolled terribly. Before the roll, she had 23 plot points, now 17. She hits the reroll button, which refunded the plot points. The second roll did not consume plot points again. After all was said and done, she ended up with a final total of 23 plot points left when she should've had 17.

**Comment by Alan19** [comment]
I believe the reroll function has been tweaked to avoid this kind of race condition
