### ISSUE TITLE
Regular Expressions for matching dice

### ISSUE THREAD

**Issue by belathus** [Alan19/TwoDee#61]
Alan asked me to write up some regular expressions to filter out the "+" that I've put in the strings for the pools. I don't know if you can grab more than one match from a single regex, but I've a few ideas that might help. If you can iterate through matches, the following might be helpful:

```
(?<die>[0-9]*[cekp]?d[0-9]+)|(?: \+ ?)(?<bonus>[0-9]+)$|(?: - ?)(?<penalty>[0-9]+)$
```
This should return a match under the group name "die" and a flat bonus under the group name "bonus" or penalty under the name "penalty." The `[cekp]?` group supports finding chaos, enhanced, kept, or plot dice; more letters would have to be added if we need more dice types. It is case sensitive, so it only supports lower case. Granted, you can always turn off the regular expression's case sensitivity.

Then there is the regex I gave you that should match every pool I'm creating with the spreadsheets:
```
^(?:(?<d12>[0-9]*d12)(?: \+ |)|)(?:(?<d10>[0-9]*d10)(?: \+ |)|)(?:(?<d8>[0-9]*d8)(?: \+ |)|)(?:(?<d6>[0-9]*d6)(?: \+ |)|)(?:(?<d4>[0-9]*d4)(?: \+ |)|)(?:(?: )(?<flat>[\+-] ?[0-9]+)|)$
```
This one will give you groups named "d12", "d10", "d8" etc. It does have the problem that it leaves a space in the "flat" group between the + or - and the number. I could edit the character sheets to omit that space, though, and that might help distinguish things without changing the regex you're using, I think.

**Comment by Alan19** [comment]
Ended up using replaceAll as that seemed to be the cleanest solution. Still, thanks for making the pools!
